on: [push, pull_request]

name: Build Lily58 Firmware with nRFMicro 1.1

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache west modules
        uses: actions/cache@v2
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('config/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: West Init
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-init
        with:
          args: 'init "-l config"'
      - name: West Update
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-update
        with:
          args: 'update'
      - name: West Config Zephyr Base
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-config
        with:
          args: 'config "--global zephyr.base-prefer configfile"'
      - name: West Zephyr Export
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-zephyr-export
        with:
          args: 'zephyr-export'
      - name: West Build (Lily58 Left)
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-build-lily58-left
        with:
          args: 'build "--pristine -s zmk/app -b nrfmicro_11 -- -DSHIELD=lily58_left -DZMK_CONFIG=/github/workspace/config"'
      - name: Lily58 Left Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Archive Liily58 Left .config
        uses: actions/upload-artifact@v2
        with:
          name: left_config
          path: build/zephyr/.config
      - name: Rename split (Lily58 Left)
        run: sudo mv build/zephyr/zmk.uf2 build/zephyr/left.uf2
      - name: Archive (Lily58 Left)
        uses: actions/upload-artifact@v2
        with:
          name: lily58
          path: build/zephyr/left.uf2
      - name: West Build (Lily58 Right)
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-build-lily58-right
        with:
          args: 'build "--pristine -s zmk/app -b nrfmicro_11 -- -DSHIELD=lily58_right -DZMK_CONFIG=/github/workspace/config"'
      - name: Lily58 Right Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Archive Lily58 Right .config
        uses: actions/upload-artifact@v2
        with:
          name: right_config
          path: build/zephyr/.config
      - name: Rename split (Lily58 Right)
        run: sudo mv build/zephyr/zmk.uf2 build/zephyr/right.uf2
      - name: Archive (Lily58 Right)
        uses: actions/upload-artifact@v2
        with:
          name: lily58
          path: build/zephyr/right.uf2
